export interface Theme {
  readonly id: string;
  readonly label: string;
  /** Overrides applied to the renderer root only, never to the host page. */
  readonly tokens: Readonly<Record<string, string>>;
}

/**
 * Each theme redefines the --seq-* tokens the renderer draws with. They are set
 * on the renderer's own element, which is why switching themes leaves the rest
 * of this page untouched.
 */
export const themes: readonly Theme[] = [
  {
    id: 'daylight',
    label: 'Daylight',
    tokens: {
      '--seq-surface': '#ffffff',
      '--seq-surface-raised': '#f6f7f9',
      '--seq-surface-sunken': '#eef0f4',
      '--seq-border': '#d8dce4',
      '--seq-text-strong': '#10131a',
      '--seq-text': '#39404e',
      '--seq-text-muted': '#6b7383',
      '--seq-lifeline': '#c3c9d4',
      '--seq-participant-fill': '#f2f4f8',
      '--seq-participant-stroke': '#c3c9d4',
      '--seq-message': '#6b7383',
      '--seq-message-spent': '#aeb5c2',
      '--seq-fragment-stroke': '#c3c9d4',
      '--seq-fragment-label-fill': '#eef0f4',
      '--seq-activation-fill': '#d8dce4',
      '--seq-note-fill': '#fff8e1',
      '--seq-note-stroke': '#e6d9a8',
      '--seq-note-text': '#4a4326',
      '--seq-accent': '#4f46e5',
      '--seq-accent-contrast': '#ffffff',
      '--seq-skipped': '#aeb5c2',
    },
  },
  {
    id: 'midnight',
    label: 'Midnight',
    tokens: {
      '--seq-surface': '#0f1116',
      '--seq-surface-raised': '#171a21',
      '--seq-surface-sunken': '#1d212a',
      '--seq-border': '#2b303b',
      '--seq-text-strong': '#f2f4f8',
      '--seq-text': '#c3c9d4',
      '--seq-text-muted': '#8b93a3',
      '--seq-lifeline': '#3a4150',
      '--seq-participant-fill': '#1d212a',
      '--seq-participant-stroke': '#3a4150',
      '--seq-message': '#8b93a3',
      '--seq-message-spent': '#4c5464',
      '--seq-fragment-stroke': '#3a4150',
      '--seq-fragment-label-fill': '#1d212a',
      '--seq-activation-fill': '#3a4150',
      '--seq-note-fill': '#2a2617',
      '--seq-note-stroke': '#4a4326',
      '--seq-note-text': '#e8dfb8',
      '--seq-accent': '#818cf8',
      '--seq-accent-contrast': '#0f1116',
      '--seq-skipped': '#4c5464',
    },
  },
  {
    id: 'blueprint',
    label: 'Blueprint',
    tokens: {
      '--seq-surface': '#0b2545',
      '--seq-surface-raised': '#13315c',
      '--seq-surface-sunken': '#0e2a50',
      '--seq-border': '#1f4b8f',
      '--seq-text-strong': '#eef4ff',
      '--seq-text': '#bcd0f0',
      '--seq-text-muted': '#7d9bc9',
      '--seq-lifeline': '#2f5f9e',
      '--seq-participant-fill': '#13315c',
      '--seq-participant-stroke': '#2f5f9e',
      '--seq-message': '#9dbaea',
      '--seq-message-spent': '#4a6f9e',
      '--seq-fragment-stroke': '#2f5f9e',
      '--seq-fragment-label-fill': '#0e2a50',
      '--seq-activation-fill': '#2f5f9e',
      '--seq-note-fill': '#123a63',
      '--seq-note-stroke': '#2f5f9e',
      '--seq-note-text': '#d6e6ff',
      '--seq-accent': '#7fd1ff',
      '--seq-accent-contrast': '#06182e',
      '--seq-skipped': '#4a6f9e',
    },
  },
  {
    id: 'ember',
    label: 'Ember',
    tokens: {
      '--seq-surface': '#fffaf5',
      '--seq-surface-raised': '#fdf0e4',
      '--seq-surface-sunken': '#f8e3d2',
      '--seq-border': '#e8c7a8',
      '--seq-text-strong': '#2c1810',
      '--seq-text': '#5a3a28',
      '--seq-text-muted': '#8a6a55',
      '--seq-lifeline': '#dcb595',
      '--seq-participant-fill': '#fdf0e4',
      '--seq-participant-stroke': '#dcb595',
      '--seq-message': '#8a6a55',
      '--seq-message-spent': '#c9a68c',
      '--seq-fragment-stroke': '#dcb595',
      '--seq-fragment-label-fill': '#f8e3d2',
      '--seq-activation-fill': '#e8c7a8',
      '--seq-note-fill': '#fff3d6',
      '--seq-note-stroke': '#e0c68a',
      '--seq-note-text': '#4a3a15',
      '--seq-accent': '#c2410c',
      '--seq-accent-contrast': '#fffaf5',
      '--seq-skipped': '#c9a68c',
    },
  },
];
